//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17_33330_1_Mid_Lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memory
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime last_modified { get; set; }
        public int priority { get; set; }
        public int user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
